#server:
#  port: 80
#  tomcat:
#    uri-encoding: UTF-8
#
#spring:
#  application:
#    name: lzx-test
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
#  aop:
#    auto: true
#
##安全验证
#management:
#  security:
#    enabled: false
#endpoints:
#  health:
#    sensitive: false
#  shutdown:
#    enabled: true

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: lzx
    password: lzx
    publisher-confirms: true