#server:
#  port: 80
#  tomcat:
#    uri-encoding: UTF-8
#
#spring:
#  application:
#    name: lzx-test
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
#  aop:
#    auto: true
#
##安全验证
#management:
#  security:
#    enabled: false
#endpoints:
#  health:
#    sensitive: false
#  shutdown:
#    enabled: true

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: lzx
    password: lzx
    #如果消息到达exchange，则ack=true，否则ack=true
    publisher-confirms: true
    #如果消息无法发送到指定的消息队列那么ReturnCallBack回调方法会被调用
    publisher-returns: true
    virtual-host: /
    template:
      mandatory: true
      reply-timeout: 600000
    #设置开启ack消息确认
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
    cache:
      channel:
        checkout-timeout: 3600
        size: 1000